"""added image_link for anime

Revision ID: 17578e682246
Revises: 37eac178af1a
Create Date: 2026-01-10 22:27:51.180310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17578e682246'
down_revision: Union[str, Sequence[str], None] = '37eac178af1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('image_link', sa.String(length=255), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'image_link')
    # ### end Alembic commands ###
