"""changed field name

Revision ID: 37eac178af1a
Revises: d846b0582e81
Create Date: 2026-01-08 08:51:58.572941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '37eac178af1a'
down_revision: Union[str, Sequence[str], None] = 'd846b0582e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('mode', sa.JSON(), nullable=False))
    op.drop_column('pack', 'modes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('modes', sqlite.JSON(), nullable=False))
    op.drop_column('pack', 'mode')
    # ### end Alembic commands ###
