"""remove synopsis

Revision ID: 6ef2939a8bf4
Revises: cfd2a70d3fdb
Create Date: 2026-01-18 09:45:54.709159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef2939a8bf4'
down_revision: Union[str, Sequence[str], None] = 'cfd2a70d3fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_anime_mode_status', 'pack', type_='unique')
    op.add_column('anime', sa.Column('synopsis', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
