"""removed artifact url and added redirects_completed field on PackDB

Revision ID: 83cff7e75d02
Revises: 707a546f3b48
Create Date: 2026-01-05 19:52:20.278445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83cff7e75d02'
down_revision: Union[str, Sequence[str], None] = '707a546f3b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('redirects_completed', sa.Integer(), nullable=False))
    op.drop_column('pack', 'artifact_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('artifact_url', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('pack', 'redirects_completed')
    # ### end Alembic commands ###
