"""added status field

Revision ID: d846b0582e81
Revises: ee192297367c
Create Date: 2026-01-08 08:24:39.698672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd846b0582e81'
down_revision: Union[str, Sequence[str], None] = 'ee192297367c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('modes', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'modes')
    # ### end Alembic commands ###
